Draft implementation of the bot comment

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -111,7 +111,6 @@ if $CODE_CHECKS ; then
     scram build -k -j $NUM_PROC code-checks USER_CODE_CHECKS_FILE="${UP_DIR}/code-checks-files.txt" > ${UP_DIR}/code-checks.log 2>&1 || ERR=true
     # run python checks
     echo "*** HERE: $(pwd) ***"
-    python3 --version
     python3 ../cms-bot/run-python-format.py --inputfile "${UP_DIR}/code-checks-files.txt" --cmsswbase "src" --outputfile "${UP_DIR}/python-checks.txt"
     cat "${UP_DIR}/python-checks.txt"
     #python3 ../cms-bot/run-python-format.py --file "${UP_DIR}/code-checks-files.txt"
@@ -123,10 +122,23 @@ if $CODE_CHECKS ; then
       grep -A 3 ': error: \|gmake: \*\*\*' ${UP_DIR}/code-checks.log | tail -24 | sed "s|$CMSSW_BASE/src/||" >> ${UP_DIR}/code-checks.md || true
       echo '```' >> ${UP_DIR}/code-checks.md
       if ! $DRY_RUN ; then
-        send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
+        #send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
         ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
       fi
-      exit 0
+      #exit 0 # avalenzu: Should we exit??
+    fi
+    if [ -s ${UP_DIR}/python-checks.txt ] ; then
+      echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
+      echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
+      echo -e '\nERROR: Ruff found formatting errors on the python files.' >> ${UP_DIR}/python-code-checks.md
+      echo '```' >> ${UP_DIR}/python-code-checks.md
+      cat ${UP_DIR}/python-checks.txt >> ${UP_DIR}/python-code-checks.md || true
+      echo '```' >> ${UP_DIR}/python-code-checks.md
+      if ! $DRY_RUN ; then
+        send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
+        ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
+      fi
+      exit 0 # avalenzu: Should we exit??
     fi
     if [ -e ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ] ; then
       mv ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ${UP_DIR}/
